### PR TITLE
Update to prompt_toolkit 2.0.x - take over jonathanslenders's works

### PR DESCRIPTION
**Pull request by boarnasia**
I patched [jonathanslenders's works](https://github.com/eliangcs/http-prompt/pull/137) into the latest source.

I don't know why this update stop for a long time, and creating new pull request is good manner or not, but I think http-prompt works with prompt_tookit 2.0.x is things I need.

Almost changes is the same as jonathanslenders's. I added only information message for KeyboardInterrupt exception on http_prompt/cli.py:169.

### CODE REVIEW

**Comment by boarnasia** [comment]
Oh, it has problems on python27.
I'll try to fix it.

**Comment by boarnasia** [comment]
Since pytest-cov v2.6, it needs pytest v3.6 over.
So I've limited pytest-cov version under 2.6 in my works.

Latest pytest ver is 4.3.1. I think it is better to update pytest minimum version to over 3.6.

**Comment by boarnasia** [comment]
[Ref issue#147](https://github.com/eliangcs/http-prompt/issues/147)

**Comment by boarnasia** [comment]
How do you think about changing prompt-toolkit version according to iPython supporting python version?

iPython have 3 version combination patterns as wrote below:

|iPython|Prompt-toolkit|Python|
|:------:|:-:|:-------:|
|5.x|1.x|2.x|
|6.x|1.x|3.3,3.4|
|7.x|2.x|>3.4|

I think most people suffer from incompatible prompt-toolkit version between http-prompt and iPython, therefore I think changing PT version according to iPython version is good idea personally.

**Comment by jayvdb** [comment]
Why not use try: except: blocks and support both.

**Comment by BoboTiG** [comment]
I merged #137, this is no more needed (thanks @boarnasia for the patch).

**Pull request closed without merging**
